#!/bin/bash
DATE=$(date +%Y%m%d)
FORTUNE=$(fortune -s|sed 's/"//g')
  DOCKER_ICINGA2_UPDATED=20160104

git pull
sed -i "s/^\ \ FREEIPA_UPDATED=.*$/ENV FREEIPA_UPDATED=$DATE/" Dockerfile
git commit -am "$FORTUNE -- $DATE"
